export const destinations = [
  {code: 'AAL', name: 'Aalborg, Dinamarca'},
  {code: 'LCG', name: 'A Coruña, España'},
  {code: 'ALC', name: 'Alicante, España'},
  {code: 'LEI', name: 'Almería, España'},
  {code: 'AMS', name: 'Ámsterdam, Países Bajos'},
  {code: 'ALG', name: 'Argel, Argelia'},
  {code: 'OVD', name: 'Asturias (Oviedo), España'},
  {code: 'ATH', name: 'Atenas, Grecia'},
  {code: 'BJL', name: 'Banjul, Gambia'},
  {code: 'BCN', name: 'Barcelona, España'},
  {code: 'BRI', name: 'Bari, Italia'},
  {code: 'BSL', name: 'Basilea, Suiza'},
  {code: 'BIA', name: 'Bastia (Córcega), Francia'},
  {code: 'BEY', name: 'Beirut, Líbano'},
  {code: 'BEG', name: 'Belgrado, Serbia'},
  {code: 'BGO', name: 'Bergen, Noruega'},
  {code: 'TXL', name: 'Berlín (Tegel), Alemania'},
  {code: 'BIO', name: 'Bilbao, España'},
  {code: 'BHX', name: 'Birmingham, Reino Unido'},
  {code: 'BLQ', name: 'Bolonia, Italia'},
  {code: 'BES', name: 'Brest, Francia'},
  {code: 'BDS', name: 'Bríndisi, Italia'},
  {code: 'BRU', name: 'Bruselas, Bélgica'},
  {code: 'OTP', name: 'Bucarest, Rumanía'},
  {code: 'BUD', name: 'Budapest, Hungría'},
  {code: 'EZE', name: 'Buenos Aires, Argentina'},
  {code: 'BOD', name: 'Burdeos, Francia'},
  {code: 'CAG', name: 'Cagliari, Italia'},
  {code: 'CWL', name: 'Cardiff, Reino Unido'},
  {code: 'CMN', name: 'Casablanca, Marruecos'},
  {code: 'CTA', name: 'Catania, Italia'},
  {code: 'EFL', name: 'Cefalonia, Grecia'},
  {code: 'CLJ', name: 'Cluj-Napoca, Rumanía'},
  {code: 'CPH', name: 'Copenhague, Dinamarca'},
  {code: 'CFU', name: 'Corfú, Grecia'},
  {code: 'KRK', name: 'Cracovia, Polonia'},
  {code: 'HER', name: 'Creta, Grecia'},
  {code: 'DKR', name: 'Dakar, Senegal'},
  {code: 'DUB', name: 'Dublín, Irlanda'},
  {code: 'DBV', name: 'Dubrovnik, Croacia'},
  {code: 'DUS', name: 'Düsseldorf, Alemania'},
  {code: 'EDI', name: 'Edimburgo, Reino Unido'},
  {code: 'EIN', name: 'Eindhoven, Países Bajos'},
  {code: 'ARN', name: 'Estocolmo, Suecia'},
  {code: 'FAO', name: 'Faro, Portugal'},
  {code: 'FEZ', name: 'Fez, Marruecos'},
  {code: 'FLR', name: 'Florencia, Italia'},
  {code: 'FUE', name: 'Fuerteventura, España'},
  {code: 'GOA', name: 'Génova, Italia'},
  {code: 'GVA', name: 'Ginebra, Suiza'},
  {code: 'GOT', name: 'Gotemburgo, Suecia'},
  {code: 'GRX', name: 'Granada, España'},
  {code: 'LPA', name: 'Gran Canaria, España'},
  {code: 'HAM', name: 'Hamburgo, Alemania'},
  {code: 'HAJ', name: 'Hanóver, Alemania'},
  {code: 'HEL', name: 'Helsinki, Finlandia'},
  {code: 'IBZ', name: 'Ibiza, España'},
  {code: 'XRY', name: 'Jerez (Cádiz), España'},
  {code: 'KGD', name: 'Kaliningrado, Rusia'},
  {code: 'AOK', name: 'Kárpatos, Grecia'},
  {code: 'IEV', name: 'Kiev, Ucrania'},
  {code: 'KGS', name: 'Kos, Grecia'},
  {code: 'LMP', name: 'Lampedusa, Italia'},
  {code: 'ACE', name: 'Lanzarote, España'},
  {code: 'SPC', name: 'La Palma, España'},
  {code: 'LCA', name: 'Lárnaca, Chipre'},
  {code: 'LIL', name: 'Lille, Francia'},
  {code: 'LIS', name: 'Lisboa, Portugal'},
  {code: 'LON', name: 'Londres, Reino Unido'},
  {code: 'LGW', name: 'Londres, Londres (Gatwick), Reino Unido'},
  {code: 'LHR', name: 'Londres, Londres (Heathrow), Reino Unido'},
  {code: 'LTN', name: 'Londres, Londres (Luton), Reino Unido'},
  {code: 'LUX', name: 'Luxemburgo, Luxemburgo'},
  {code: 'LYS', name: 'Lyon, Francia'},
  {code: 'FNC', name: 'Madeira, Portugal'},
  {code: 'MAD', name: 'Madrid, España'},
  {code: 'AGP', name: 'Málaga, España'},
  {code: 'PMI', name: 'Mallorca, España'},
  {code: 'MLA', name: 'Malta, Malta'},
  {code: 'MAN', name: 'Manchester, Reino Unido'},
  {code: 'RAK', name: 'Marrakech, Marruecos'},
  {code: 'MRS', name: 'Marsella, Francia'},
  {code: 'MAH', name: 'Menorca, España'},
  {code: 'JMK', name: 'Mikonos, Grecia'},
  {code: 'MXP', name: 'Milán, Italia'},
  {code: 'MSQ', name: 'Minsk, Bielorrusia'},
  {code: 'MOW', name: 'Moscú, Rusia'},
  {code: 'DME', name: 'Moscú, Moscú (Domodedovo), Rusia'},
  {code: 'MUC', name: 'Múnich, Alemania'},
  {code: 'NDR', name: 'Nador, Marruecos'},
  {code: 'NTE', name: 'Nantes, Francia'},
  {code: 'NAP', name: 'Nápoles, Italia'},
  {code: 'NCE', name: 'Niza, Francia'},
  {code: 'NUE', name: 'Nuremberg, Alemania'},
  {code: 'OLB', name: 'Olbia, Italia'},
  {code: 'OPO', name: 'Oporto, Portugal'},
  {code: 'ORN', name: 'Orán, Argelia'},
  {code: 'OSL', name: 'Oslo, Noruega'},
  {code: 'PMO', name: 'Palermo, Italia'},
  {code: 'PNA', name: 'Pamplona, España'},
  {code: 'PAR', name: 'París, Francia'},
  {code: 'CDG', name: 'París, Paris (Charles de Gaulle), Francia'},
  {code: 'ORY', name: 'París, París (Orly), Francia'},
  {code: 'PSA', name: 'Pisa (Toscana), Italia'},
  {code: 'PRG', name: 'Praga, República Checa'},
  {code: 'PVK', name: 'Préveza, Grecia'},
  {code: 'PUJ', name: 'Punta Cana, República Dominicana'},
  {code: 'KEF', name: 'Reikiavik, Islandia'},
  {code: 'RNS', name: 'Rennes, Francia'},
  {code: 'RHO', name: 'Rodas, Grecia'},
  {code: 'FCO', name: 'Roma (Fiumicino), Italia'},
  {code: 'RTM', name: 'Róterdam, Países Bajos'},
  {code: 'LED', name: 'San Petersburgo, Rusia'},
  {code: 'EAS', name: 'San Sebastián, España'},
  {code: 'SDR', name: 'Santander, España'},
  {code: 'SCQ', name: 'Santiago, España'},
  {code: 'JTR', name: 'Santorini, Grecia'},
  {code: 'SVQ', name: 'Sevilla, España'},
  {code: 'SPU', name: 'Split, Croacia'},
  {code: 'STR', name: 'Stuttgart, Alemania'},
  {code: 'TLL', name: 'Tallin, Estonia'},
  {code: 'TNG', name: 'Tánger, Marruecos'},
  {code: 'TLV', name: 'Tel Aviv, Israel'},
  {code: 'TCI', name: 'Tenerife, España'},
  {code: 'TFN', name: 'Tenerife, Tenerife Norte, España'},
  {code: 'TFS', name: 'Tenerife, Tenerife Sur, España'},
  {code: 'SKG', name: 'Tesalónica, Grecia'},
  {code: 'TLS', name: 'Toulouse, Francia'},
  {code: 'TUN', name: 'Túnez, Túnez'},
  {code: 'TRN', name: 'Turin, Italia'},
  {code: 'VLC', name: 'Valencia, España'},
  {code: 'VLL', name: 'Valladolid, España'},
  {code: 'WAW', name: 'Varsovia, Polonia'},
  {code: 'VCE', name: 'Venecia, Italia'},
  {code: 'VRN', name: 'Verona, Italia'},
  {code: 'VIE', name: 'Viena, Austria'},
  {code: 'VGO', name: 'Vigo, España'},
  {code: 'ZAD', name: 'Zadar, Croacia'},
  {code: 'ZAG', name: 'Zagreb, Croacia'},
  {code: 'ZTH', name: 'Zante, Grecia'},
  {code: 'ZAZ', name: 'Zaragoza, España'},
  {code: 'ZRH', name: 'Zúrich, Suiz'}
];
